version: '3.2'
services:
  url-shortener:
    image: renatofialho/testurlshortener:latest
    environment:
      - REDIS_HOSTNAME=url-shortener-redis
      - REDIS_PORT=6379
    depends_on:
      - "url-shortener-redis"
    ports:
      - 8080:8080
  url-shortener-redis:
    image: redis:latest
    
